# Generated by Django 4.2 on 2025-06-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0018_remove_artigo_ativo_artigo_visivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='ordem',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
