# Generated by Django 4.2 on 2025-06-23 03:03

import A_Lei_no_NT.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0021_alter_artigo_conteudo_html_alter_artigo_slug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Midia',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='midia',
        ),
        migrations.AddField(
            model_name='area',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='arquivo_word',
            field=models.FileField(blank=True, null=True, upload_to=A_Lei_no_NT.utils.renomear_arquivo_word),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo_html',
            field=models.TextField(default='<p></p>'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to=A_Lei_no_NT.utils.renomear_imagem_capa),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, default='artigo_sem_slug', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(blank=True, default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artigo',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
    ]
