# Generated by Django 4.2 on 2026-03-12 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('serie', models.CharField(blank=True, max_length=255)),
                ('resumo', models.TextField(blank=True)),
                ('conteudo_html', models.TextField(blank=True)),
                ('pdf_tablet', models.FileField(blank=True, null=True, upload_to='pdfs/sermoes/tablet/')),
                ('pdf_a4', models.FileField(blank=True, null=True, upload_to='pdfs/sermoes/a4/')),
                ('pdf_a5', models.FileField(blank=True, null=True, upload_to='pdfs/sermoes/a5/')),
                ('docx_a4', models.FileField(blank=True, null=True, upload_to='docs/sermoes/')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='imagens/sermoes/')),
                ('visivel', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sermão',
                'verbose_name_plural': 'Sermões',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
