# Generated by Django 5.0.6 on 2024-07-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0004_alter_artigo_caminho_arquivo_docx'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='nome_arquivo_txt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='caminho_arquivo_docx',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
