# Generated by Django 5.0.6 on 2024-07-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0005_artigo_conteudo_artigo_nome_arquivo_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(default='Conteúdo não disponível'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='nome_arquivo_txt',
            field=models.CharField(default='arquivo.txt', max_length=200),
        ),
    ]
