# Generated by Django 5.0.6 on 2024-07-17 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0009_set_default_ordem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='conteudo',
            new_name='conteudo_html',
        ),
        migrations.RenameField(
            model_name='midia',
            old_name='caminho',
            new_name='arquivo',
        ),
    ]
