# Generated by Django 4.2 on 2025-05-16 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0011_artigo_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='area',
            name='nome_area',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='midia',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nome_autor',
        ),
        migrations.RemoveField(
            model_name='midia',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='midia',
            name='nome_midia',
        ),
        migrations.RemoveField(
            model_name='midia',
            name='tipo',
        ),
        migrations.AddField(
            model_name='area',
            name='nome',
            field=models.CharField(default='Geral', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nome',
            field=models.CharField(default='Geral', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midia',
            name='titulo',
            field=models.CharField(default='Geral', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='midia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='A_Lei_no_NT.midia'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='arquivo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
