# Generated by Django 4.2 on 2025-06-17 21:42

import A_Lei_no_NT.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0012_remove_area_descricao_remove_area_nome_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to=A_Lei_no_NT.utils.renomear_imagem_capa),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
