# Generated by Django 4.2 on 2025-06-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0013_artigo_imagem_capa_alter_artigo_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='imagem',
        ),
        migrations.AddField(
            model_name='artigo',
            name='arquivo_word',
            field=models.FileField(blank=True, null=True, upload_to='uploads/docx/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo_html',
            field=models.TextField(blank=True),
        ),
    ]
