# Generated by Django 4.2 on 2025-06-21 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0014_remove_artigo_imagem_artigo_arquivo_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='area',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='midia',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='ordem',
        ),
        migrations.AddField(
            model_name='artigo',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='publicado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artigo',
            name='arquivo_word',
            field=models.FileField(blank=True, null=True, upload_to='documentos/artigos/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/artigos/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
