# Generated by Django 4.2 on 2025-06-22 05:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0015_remove_artigo_area_remove_artigo_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='A_Lei_no_NT.area'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artigo',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to='midia/artigos/'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='A_Lei_no_NT.autor'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo_html',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='publicado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
