# Generated by Django 4.2 on 2025-06-22 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0016_artigo_area_artigo_data_publicacao_artigo_midia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='arquivo_word',
            field=models.FileField(blank=True, null=True, upload_to='artigos/word/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])]),
        ),
    ]
