# Generated by Django 4.2 on 2025-06-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0017_alter_artigo_arquivo_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='ativo',
        ),
        migrations.AddField(
            model_name='artigo',
            name='visivel',
            field=models.BooleanField(default=True, verbose_name='Visível ao público'),
        ),
    ]
