# Generated by Django 4.2 on 2025-06-22 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0019_alter_artigo_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
