# Generated by Django 4.2 on 2025-06-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0020_alter_artigo_conteudo_html_alter_artigo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='conteudo_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
