# Generated by Django 4.2 on 2025-06-23 04:03

import A_Lei_no_NT.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0022_delete_midia_remove_artigo_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='arquivo_word',
            field=models.FileField(blank=True, null=True, upload_to=A_Lei_no_NT.models.caminho_arquivo),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to=A_Lei_no_NT.models.caminho_imagem),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='ordem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='publicado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
