# Generated by Django 4.2 on 2025-09-14 02:10

import A_Lei_no_NT.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0023_alter_artigo_arquivo_word_alter_artigo_conteudo_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to=A_Lei_no_NT.models.caminho_pdf),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='arquivo_word',
            field=models.FileField(blank=True, null=True, upload_to='uploads/artigos/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/artigos/'),
        ),
    ]
