# Generated by Django 4.2 on 2025-10-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A_Lei_no_NT", "0024_artigo_arquivo_pdf_alter_artigo_arquivo_word_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="artigo",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
