# Generated by Django 4.2 on 2025-12-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A_Lei_no_NT", "0026_alter_artigo_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="views",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="artigo",
            name="slug",
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
