# Generated by Django 5.0.2 on 2024-06-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=\1Blog/Imagens/')),
                ('content', models.TextField()),
            ],
        ),
    ]
