# Generated by Django 5.0.6 on 2024-07-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0002_area_artigo_autor_midia_delete_texto_artigo_autor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='texto',
        ),
        migrations.AddField(
            model_name='artigo',
            name='caminho_arquivo_docx',
            field=models.CharField(default='C:\\Users\\Wanderley\\Apps\\Albino_Marks\\A_Lei_no_NT\\Templates\\A_Lei_no_NT\\Textos\\DOCX', max_length=255),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='midia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='A_Lei_no_NT.midia'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
