# Generated by Django 5.0.6 on 2024-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0003_remove_artigo_texto_artigo_caminho_arquivo_docx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='caminho_arquivo_docx',
            field=models.CharField(max_length=255),
        ),
    ]
