# Generated by Django 5.0.6 on 2024-07-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0006_alter_artigo_conteudo_alter_artigo_nome_arquivo_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='ordem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='nome_arquivo_txt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
