# Generated by Django 5.0.6 on 2024-07-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0007_artigo_ordem_alter_artigo_nome_arquivo_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='caminho_arquivo_docx',
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='nome_arquivo_txt',
        ),
        migrations.AddField(
            model_name='area',
            name='descricao',
            field=models.TextField(default='Descrição padrão temporária'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='midia',
            name='nome_midia',
            field=models.CharField(default='Nome Padrão Temporário', max_length=200),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='midia',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='ordem',
            field=models.IntegerField(),
        ),
    ]
