# Generated by Django 5.0.6 on 2024-07-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Lei_no_NT', '0010_rename_conteudo_artigo_conteudo_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='artigos/'),
        ),
    ]
