# Generated by Django 4.2 on 2025-10-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A_Lei_no_NT", "0025_alter_artigo_slug_alter_artigo_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
